name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write  # ✅ Needed for SARIF upload

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
          push-fixes: pull-request
          args: --apply-fixes
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

      - name: Check GITHUB_TOKEN availability
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "❌ GITHUB_TOKEN is not set!"
            exit 1
          else
            echo "✅ GITHUB_TOKEN is set. Length: ${#GITHUB_TOKEN}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          category: Qodana
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
